apiVersion: v1
kind: Service
metadata:
  name: taxi-booking-service
  namespace: taxi
spec:
  type: LoadBalancer
  selector:
    app: taxi-booking
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
